project_name: json2csv
report_sizes: true

env_files:
  github_token: ~/.github_token

before:
  hooks:
    - go mod download
    - go mod tidy
    - go run golang.org/x/vuln/cmd/govulncheck@latest -test ./...
    - go run github.com/securego/gosec/v2/cmd/gosec@latest -exclude=G107 -quiet ./...
    - go run github.com/go-critic/go-critic/cmd/gocritic@latest check -enableAll ./...

builds:
  -
    id: default
    env: [ CGO_ENABLED=0 ]
    goos: [ linux, windows ]
    goarch: [ amd64, arm64 ]

  - # HACK for macOS Ventura (13.x), which not supported UPX
    id: macOS_only
    env: [ CGO_ENABLED=0 ]
    goos: [ darwin ]
    goarch: [ amd64, arm64 ]

upx:
  - ids: [ default ]
    enabled: true
    compress: best
    lzma: true
    brute: true

release:
  ids: [ default, macOS_only ]
  draft: true
  replace_existing_draft: true
  target_commitish: "{{ .Commit }}"
  #  discussion_category_name: General
  prerelease: auto
  mode: replace
  header: |
    ## ⚙️ The `{{ .Tag }}` release
  footer: |
    ## Install or update
    
    For native Go installation (any platforms):
    
    ```console
    go install github.com/koddr/json2csv@latest
    ```

    For [Homebrew][brew_url] users (GNU/Linux, macOS):
    
    ```console
    brew upgrade koddr/tap/json2csv
    ```
    
    > 💡 Note: See the [`Wiki page`][wiki_url] to understand structures of JSON files and get general recommendations for preparing the input data.
    
    ## Your help to improve project
    
    I'd be truly grateful for help with:
    
    - Creating tests (and/or benchmarks) for code
    - Improving existing functions, structs, or tests
    - Feature requests with interesting functions that would be good to add
    
    Your PRs & issues are welcome! Thanks 😉
    
    [brew_url]: https://brew.sh
    [wiki_url]: https://github.com/koddr/json2csv/wiki
  disable: false
  skip_upload: false

brews:
  - tap:
      owner: koddr
      name: homebrew-tap
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
      pull_request:
        enabled: true
      git:
        url: "git@github.com:koddr/homebrew-tap.git"
        private_key: "{{ .Env.PRIVATE_KEY_PATH }}"
    commit_author:
      name: Vic Shóstak
      email: koddr.me@gmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    caveats: |
      After install json2csv, prepare folder with your data input in the *.json format, create JSON files with intents and filter.

      💡 Note: See the repository's Wiki page (https://github.com/koddr/json2csv/wiki) to understand structures of JSON files and get general recommendations for preparing the input data.

      Next, run json2csv parser with options:

      $ json2csv -json /path/to/input/json/folder -intents /path/to/intents-file.json -filter /path/to/filter-file.json -output /path/to/output/csv/folder -content-field message -min-word-len 5 -chunk 1000
      
      Done! Output CSV file(s) has a default comma (,) separators between columns.
    homepage: "https://github.com/koddr/{{ .ProjectName }}"
    description: |
      The parser can read given folder with *.json files, filtering and qualifying input data with intent & stop words dictionaries and save results to CSV files by given chunk size.
    license: Apache 2.0
    skip_upload: false

nfpms:
  - maintainer: Vic Shóstak <koddr.me@gmail.com>
    description: |
      The parser can read given folder with *.json files, filtering and qualifying input data with intent & stop words dictionaries and save results to CSV files by given chunk size.
    homepage: "https://github.com/koddr/{{ .ProjectName }}"
    license: Apache 2.0
    formats: [ deb, rpm, apk, archlinux ]

dockers:
  - id: "{{ .ProjectName }}"
    ids: [ default ]
    image_templates:
      - "koddr/{{ .ProjectName }}:latest"
      - "koddr/{{ .ProjectName }}:{{ .Tag }}"
      - "koddr/{{ .ProjectName }}:v{{ .Major }}"
      - "koddr/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--platform=linux/amd64"
    skip_push: false
    push_flags:
      - --tls-verify=false

archives:
  - format_overrides:
      - goos: windows
        format: zip
    files: [ LICENSE, README.md ]
    rlcp: true

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude: [ "^*.md:", "^*.yml:" ]
  groups:
    - title: Features
      regexp: ^.*?(F|f)eature.*?$
      order: 0
    - title: Bug fixes
      regexp: ^.*?((B|b)ug)|((F|f)ix).*?$
      order: 1
    - title: Improvements
      regexp: ^.*?(I|i)mprove.*?$
      order: 2
    - title: Updates
      regexp: ^.*?(U|u)pdate.*?$
      order: 3
    - title: Security issues
      regexp: ^.*?(S|s)ecurity.*?$
      order: 4
    - title: Others
      order: 999
